### ISSUE TITLE
Is it still in active development?

### ISSUE THREAD

**Issue by joachimesque** [sebastiangreger/kirby3-sendmentions#12]
Hi Sebastian!
Is this plugin still actively developed?
I can't seem to get it to work on the latest version of Kirby, as I get this error:

```
Non-static method sgkirby\SendMentions\Migration::run() should not be called statically
```

Cheers!

**Comment by sebastiangreger** [comment]
Bonjour Joachim,

I am sorry to inform you that I haven't had the resources to keep this plugin up-to-date in a long while, and it is actually on a list of side projects I aim to officially retire/archive by the end of this year as I don't see myself able to maintain it :cry:

The particular error you are pointing out indicated an issue with PHP8 (essentially, there's a `static` keyword missing for that method in question), which Kirby now requires – I have never tested this plugin on PHP8. 

There have also been some major changes in the panel Vue components back in K3.6 (over a year ago) which would require massive work on this plugin. So unfortunately I believe this has essentially reached a dead end.
