### ISSUE TITLE
Support for brid.gy

### ISSUE THREAD

**Issue by MaluNoPeleke** [sebastiangreger/kirby3-sendmentions#9]
Can you add support for [brid.gy publishing](https://brid.gy/about#publishing)?

**Comment by sebastiangreger** [comment]
AFAIK, *brid.gy publish* is a webmention endpoint as any other. It should be sufficient to place an invisible link to one of the documented target URLs in your content. So if your text for example includes `<a href="https://brid.gy/publish/twitter"></a>` and you have Sendmentions configured to send out webmentions to all URLs on publish, this should trigger the workflows you have configured on brid.gy's side (side note: this example from the brid.gy documentation is not good practice in terms of a11y – screen readers would read out that URL – so the markup should probably be hidden in a better way than putting out an empty element…).

I don't have hands-on experience with this, though; the above is only based on what I read from the documentation. But essentially all that is needed is a link to one of those specified URLs in the content (see above) and a ping to the webmention endpoint on brid.gy (that's the core functionality of Sendmentions, pinging all URLs contained in your content).

Edit: Oh, and of course the page template has to use the correct Microformat markup (HTML structure and class attributes) for brid.gy to pick the applicable content, as outlined in their documentation's examples.
